import unreal as u
level=u.get_editor_subsystem(u.LevelEditorSubsystem)
actors=u.get_editor_subsystem(u.EditorActorSubsystem)
level.load_level('/Game/Factory/Maps/ClassicFactoryArmed')
pickup=next(a for a in actors.get_all_level_actors() if a.actor_has_tag('FactoryStartingWeapon'))
start=next(a for a in actors.get_all_level_actors() if isinstance(a,u.PlayerStart))
target=start.get_actor_location()-u.Vector(0,0,40)
# Delay the overlap until Character BeginPlay has initialized its inventory.
# A short, invisible startup pickup track uses the existing tested pickup blueprint.
origin=target+u.Vector(240,0,0)
pickup.set_actor_location(origin,False,True)
pickup.set_actor_hidden_in_game(True)
seq=u.load_asset('/Game/Factory/Startup/GrantStartingRifle')
if not seq:seq=u.AssetToolsHelpers.get_asset_tools().create_asset('GrantStartingRifle','/Game/Factory/Startup',u.LevelSequence,u.LevelSequenceFactoryNew())
for binding in seq.get_bindings():binding.remove()
seq.set_display_rate(u.FrameRate(30,1));seq.set_playback_start(0);seq.set_playback_end(30)
binding=seq.add_possessable(pickup)
track=binding.add_track(u.MovieScene3DTransformTrack)
section=track.add_section();section.set_range(0,30)
channels=section.get_all_channels()
for i,(first,last) in enumerate(zip([origin.x,origin.y,origin.z],[target.x,target.y,target.z])):
    channels[i].add_key(u.FrameNumber(0),first)
    channels[i].add_key(u.FrameNumber(6),first)
    channels[i].add_key(u.FrameNumber(12),last)
    channels[i].add_key(u.FrameNumber(29),last)
for i in range(3,6):channels[i].set_default(0)
for i in range(6,9):channels[i].set_default(1)
for a in actors.get_all_level_actors():
    if a.actor_has_tag('FactoryWeaponStartup'):actors.destroy_actor(a)
director=actors.spawn_actor_from_class(u.LevelSequenceActor,u.Vector())
director.set_sequence(seq)
settings=director.get_editor_property('playback_settings');settings.set_editor_property('auto_play',True)
director.set_editor_property('playback_settings',settings)
director.set_editor_property('tags',['FactoryWeaponStartup'])
u.EditorAssetLibrary.save_loaded_asset(seq)
assert level.save_current_level()
